// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void turnon_Animation( lv_obj_t *TargetObject, int delay);
void passed_Animation( lv_obj_t *TargetObject, int delay);
void turndown_Animation( lv_obj_t *TargetObject, int delay);
void turnupkeyboard_Animation( lv_obj_t *TargetObject, int delay);
void scalewin_Animation( lv_obj_t *TargetObject, int delay);
void openwin_Animation( lv_obj_t *TargetObject, int delay);
void fadeout_Animation( lv_obj_t *TargetObject, int delay);
void fadein_Animation( lv_obj_t *TargetObject, int delay);
void EjectRight_Animation( lv_obj_t *TargetObject, int delay);
void EjectLeft_Animation( lv_obj_t *TargetObject, int delay);
void amplify_Animation( lv_obj_t *TargetObject, int delay);
void reduce_Animation( lv_obj_t *TargetObject, int delay);
void movetoleft_Animation( lv_obj_t *TargetObject, int delay);
void movetocenter_Animation( lv_obj_t *TargetObject, int delay);
void topon_Animation( lv_obj_t *TargetObject, int delay);
void topoff_Animation( lv_obj_t *TargetObject, int delay);
void lefton_Animation( lv_obj_t *TargetObject, int delay);
void leftoff_Animation( lv_obj_t *TargetObject, int delay);
void cardin_Animation( lv_obj_t *TargetObject, int delay);
void turnmenuon_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_setup
void ui_setup_screen_init(void);
void ui_event_setup( lv_event_t * e);
lv_obj_t *ui_setup;
lv_obj_t *ui_header_group1;
lv_obj_t *ui_wizard_group1;
lv_obj_t *ui_dot3;
lv_obj_t *ui_line2;
lv_obj_t *ui_dot4;
lv_obj_t *ui_line4;
lv_obj_t *ui_dot6;
lv_obj_t *ui_wifi_group;
lv_obj_t *ui_wlan_image;
lv_obj_t *ui_wifi_Spinner;
lv_obj_t *ui_Network_panel;
lv_obj_t *ui_wifi_input_panel;
void ui_event_wifiTextArea( lv_event_t * e);
lv_obj_t *ui_wifiTextArea;
void ui_event_cancel_btn( lv_event_t * e);
lv_obj_t *ui_cancel_btn;
lv_obj_t *ui_Label12;
void ui_event_cancel_btn1( lv_event_t * e);
lv_obj_t *ui_cancel_btn1;
lv_obj_t *ui_Label13;
void ui_event_Keyboard1( lv_event_t * e);
lv_obj_t *ui_Keyboard1;


// SCREEN: ui_mqtt_Setting
void ui_mqtt_Setting_screen_init(void);
void ui_event_mqtt_Setting( lv_event_t * e);
lv_obj_t *ui_mqtt_Setting;
lv_obj_t *ui_header_group2;
lv_obj_t *ui_wizard_group2;
lv_obj_t *ui_dot7;
lv_obj_t *ui_line5;
lv_obj_t *ui_dot8;
lv_obj_t *ui_line6;
lv_obj_t *ui_dot9;
lv_obj_t *ui_ok_group;
lv_obj_t *ui_mqtt_Spinner;
lv_obj_t *ui_mqtt_image;
void ui_event_Button_Button( lv_event_t * e);
lv_obj_t *ui_Button;
lv_obj_t *ui_info_text;
lv_obj_t *ui_mqtt_panel;
void ui_event_subscript_text( lv_event_t * e);
lv_obj_t *ui_subscript_text;
void ui_event_puliish_text( lv_event_t * e);
lv_obj_t *ui_puliish_text;
void ui_event_clintid_text( lv_event_t * e);
lv_obj_t *ui_clintid_text;
void ui_event_clint_addr_text( lv_event_t * e);
lv_obj_t *ui_clint_addr_text;
void ui_event_username_text( lv_event_t * e);
lv_obj_t *ui_username_text;
void ui_event_password_text( lv_event_t * e);
lv_obj_t *ui_password_text;
void ui_event_port_text( lv_event_t * e);
lv_obj_t *ui_port_text;
void ui_event_Keyboard2( lv_event_t * e);
lv_obj_t *ui_Keyboard2;


// SCREEN: ui_setting_param
void ui_setting_param_screen_init(void);
void ui_event_setting_param( lv_event_t * e);
lv_obj_t *ui_setting_param;
lv_obj_t *ui_header_group;
lv_obj_t *ui_wizard_group;
lv_obj_t *ui_dot1;
lv_obj_t *ui_line1;
lv_obj_t *ui_dot2;
lv_obj_t *ui_line3;
lv_obj_t *ui_dot5;
lv_obj_t *ui_content_group;
lv_obj_t *ui_Label_Alarm_setting;
lv_obj_t *ui_footer_group;
lv_obj_t *ui_Roller_Temp;
lv_obj_t *ui_Image9;
lv_obj_t *ui_temp_roller;
lv_obj_t *ui_Roller_Humi;
lv_obj_t *ui_Image10;
lv_obj_t *ui_humi_roller;
lv_obj_t *ui_Label_Temp1;
lv_obj_t *ui_Label_Humi1;
lv_obj_t *ui_BTN_Choose;
void ui_event_BTN_Choose_Top( lv_event_t * e);
lv_obj_t *ui_BTN_Choose_Top;
lv_obj_t *ui_Image_Choose;


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main( lv_event_t * e);
lv_obj_t *ui_main;
lv_obj_t *ui_wallpaper_main_img;
lv_obj_t *ui_Panel1;
void ui_event_win_btn( lv_event_t * e);
lv_obj_t *ui_win_btn;
void ui_event_button_panel( lv_event_t * e);
lv_obj_t *ui_button_panel;
void ui_event_wifi( lv_event_t * e);
lv_obj_t *ui_wifi;
void ui_event_voice( lv_event_t * e);
lv_obj_t *ui_voice;
lv_obj_t *ui_time;
lv_obj_t *ui_monitor;
lv_obj_t *ui_Temp_label;
lv_obj_t *ui_sensor_chart;
lv_obj_t *ui_temp_arc;
lv_obj_t *ui_Image7;
lv_obj_t *ui_humi_arc;
lv_obj_t *ui_Image8;
lv_obj_t *ui_bar_panel;
lv_obj_t *ui_cpu_label;
lv_obj_t *ui_Cpu_Bar;
lv_obj_t *ui_ram_label;
lv_obj_t *ui_ram_Bar;
lv_obj_t *ui_rom_label;
lv_obj_t *ui_rom_Bar;
lv_obj_t *ui_Setting_Pannel;
void ui_event_sys_display_panel( lv_event_t * e);
lv_obj_t *ui_sys_display_panel;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label5;
void ui_event_sys_win_panel( lv_event_t * e);
lv_obj_t *ui_sys_win_panel;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label2;
void ui_event_sys_network_panel( lv_event_t * e);
lv_obj_t *ui_sys_network_panel;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label3;
void ui_event_sys_info_panel( lv_event_t * e);
lv_obj_t *ui_sys_info_panel;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_sys_main_panel;
lv_obj_t *ui_main_display_panel;
void ui_event_set_backlight_panel( lv_event_t * e);
lv_obj_t *ui_set_backlight_panel;
lv_obj_t *ui_backlight_text;
lv_obj_t *ui_img_right2;
void ui_event_set_resolution_panel( lv_event_t * e);
lv_obj_t *ui_set_resolution_panel;
lv_obj_t *ui_backlight_text1;
lv_obj_t *ui_Dropdown1;
void ui_event_set_monitor_panel( lv_event_t * e);
lv_obj_t *ui_set_monitor_panel;
lv_obj_t *ui_monitor_text;
void ui_event_Switch1( lv_event_t * e);
lv_obj_t *ui_Switch1;
lv_obj_t *ui_main_win_panel;
void ui_event_Disk_panel( lv_event_t * e);
lv_obj_t *ui_Disk_panel;
lv_obj_t *ui_disk_letter;
lv_obj_t *ui_disk_img;
lv_obj_t *ui_disk_free_img;
lv_obj_t *ui_disk_storge_text;
void ui_event_download_panel( lv_event_t * e);
lv_obj_t *ui_download_panel;
lv_obj_t *ui_download_img;
lv_obj_t *ui_download_letter1;
lv_obj_t *ui_fixation;
void ui_event_desktop_panel( lv_event_t * e);
lv_obj_t *ui_desktop_panel;
lv_obj_t *ui_desktop_img;
lv_obj_t *ui_desktop_letter1;
lv_obj_t *ui_fixation1;
void ui_event_photo_panel( lv_event_t * e);
lv_obj_t *ui_photo_panel;
lv_obj_t *ui_desktop_img1;
lv_obj_t *ui_photo_letter1;
lv_obj_t *ui_fixation2;
void ui_event_main_filesys_panel( lv_event_t * e);
lv_obj_t *ui_main_filesys_panel;
lv_obj_t *ui_main_network_panel;
lv_obj_t *ui_main_info_panel;
lv_obj_t *ui_debugArea;
lv_obj_t *ui_back_panel;
void ui_event_close( lv_event_t * e);
lv_obj_t *ui_close;
void ui_event_scale( lv_event_t * e);
lv_obj_t *ui_scale;
void ui_event_hide( lv_event_t * e);
lv_obj_t *ui_hide;
lv_obj_t *ui_Head;
lv_obj_t *ui_name;
lv_obj_t *ui_panel_name;
lv_obj_t *ui_system_ctrl_panel;
void ui_event_wifi_control( lv_event_t * e);
lv_obj_t *ui_wifi_control;
lv_obj_t *ui_wifi_icon5;
lv_obj_t *ui_wifi_icon6;
lv_obj_t *ui_midline;
void ui_event_ble_control( lv_event_t * e);
lv_obj_t *ui_ble_control;
lv_obj_t *ui_ble_icon13;
lv_obj_t *ui_wifi_icon2;
lv_obj_t *ui_midline1;
lv_obj_t *ui_battery_control;
lv_obj_t *ui_ble_icon1;
lv_obj_t *ui_wifi_icon3;
lv_obj_t *ui_midline2;
lv_obj_t *ui_mode_control;
lv_obj_t *ui_ble_icon2;
lv_obj_t *ui_wifi_icon4;
lv_obj_t *ui_midline3;
void ui_event_backlight_control__slider( lv_event_t * e);
lv_obj_t *ui_backlight_control__slider;
void ui_event_voice_control__slider( lv_event_t * e);
lv_obj_t *ui_voice_control__slider;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Image6;
lv_obj_t *ui_menu;
void ui_event_search_TextArea( lv_event_t * e);
lv_obj_t *ui_search_TextArea;
lv_obj_t *ui_search_img;
void ui_event_setting( lv_event_t * e);
lv_obj_t *ui_setting;
void ui_event_file( lv_event_t * e);
lv_obj_t *ui_file;
void ui_event_pc( lv_event_t * e);
lv_obj_t *ui_pc;
void ui_event_Keyboard( lv_event_t * e);
lv_obj_t *ui_Keyboard;
void ui_event_message_panel( lv_event_t * e);
lv_obj_t *ui_message_panel;
lv_obj_t *ui_backlight_setting;
void ui_event_backlight_Slider( lv_event_t * e);
lv_obj_t *ui_backlight_Slider;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bg[1] = {&ui_img_bg1_png};
const lv_img_dsc_t *ui_imgset_btn[1] = {&ui_img_btn1_png};
const lv_img_dsc_t *ui_imgset_file_x[1] = {&ui_img_file_25x25_png};
const lv_img_dsc_t *ui_imgset_wifi_[2] = {&ui_img_wifi_13_png, &ui_img_wifi_15_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void turnon_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 200, -35 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void passed_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 50);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 0, 20 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 50);
lv_anim_set_playback_delay(&PropertyAnimation_0, 10);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}
void turndown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 200 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void turnupkeyboard_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 200, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 220 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void scalewin_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_0, 0, -40 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_width );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 500);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_1, 0, -40 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_height );
lv_anim_start(&PropertyAnimation_1);

}
void openwin_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 800);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_1, -200, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_width );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 300);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_2, -200, 0 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_height );
lv_anim_start(&PropertyAnimation_2);

}
void fadeout_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void fadein_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);

}
void EjectRight_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 600);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -140, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void EjectLeft_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 600);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 140, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void amplify_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_0, 0, 288 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 400);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_1, 0, 150 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 200);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_2, 0, 250 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_2);

}
void reduce_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_0, 288, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 400);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_1, 150, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}
void movetoleft_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, -410 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}
void movetocenter_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -410, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}
void topon_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -20, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 100);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void topoff_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, -50 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void lefton_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -500, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void leftoff_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, -100 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 255, 0 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
lv_anim_start(&PropertyAnimation_1);

}
void cardin_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 100, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}
void turnmenuon_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 200, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_setup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      topon_Animation(ui_wizard_group1, 300);
      lefton_Animation(ui_wifi_group, 500);
      fadein_Animation(ui_wifi_group, 500);
      scan_wifi_func( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      topoff_Animation(ui_wizard_group1, 0);
      leftoff_Animation(ui_wifi_group, 100);
      fadeout_Animation(ui_Network_panel, 200);
      clean_resources( e );
}
}
void ui_event_wifiTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_wifiTextArea);
      turnupkeyboard_Animation(ui_Keyboard1, 0);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_cancel_btn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wifi_input_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_cancel_btn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_wifi_input_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      connect_wifi_event( e );
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      turndown_Animation(ui_Keyboard1, 0);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ( e );
}
}
void ui_event_mqtt_Setting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      topon_Animation(ui_wizard_group2, 300);
      lefton_Animation(ui_ok_group, 100);
      fadein_Animation(ui_ok_group, 200);
      fadein_Animation(ui_mqtt_panel, 100);
}
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      topoff_Animation(ui_wizard_group2, 0);
      leftoff_Animation(ui_ok_group, 100);
      fadeout_Animation(ui_mqtt_panel, 200);
}
}
void ui_event_Button_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      set_mqtt_param_func( e );
}
}
void ui_event_subscript_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_subscript_text);
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_puliish_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_puliish_text);
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_clintid_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_clintid_text);
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_clint_addr_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      _ui_keyboard_set_target(ui_Keyboard2,  ui_clint_addr_text);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_username_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      _ui_keyboard_set_target(ui_Keyboard2,  ui_username_text);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_password_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      _ui_keyboard_set_target(ui_Keyboard2,  ui_password_text);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_port_text( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard2,  ui_port_text);
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      turnupkeyboard_Animation(ui_Keyboard2, 0);
      show_text_sync( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      show_text_sync( e );
}
}
void ui_event_Keyboard2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      turndown_Animation(ui_Keyboard2, 0);
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      get_keyboard_value( e );
}
}
void ui_event_setting_param( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      topon_Animation(ui_wizard_group, 0);
      fadein_Animation(ui_footer_group, 100);
      _ui_opacity_set( ui_footer_group, 0);
      fadein_Animation(ui_content_group, 200);
}
if ( event_code == LV_EVENT_SCREEN_UNLOAD_START) {
      fadeout_Animation(ui_content_group, 100);
      topoff_Animation(ui_wizard_group, 0);
}
}
void ui_event_BTN_Choose_Top( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      save_alarm_parameter( e );
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 200, 400, &ui_main_screen_init);
}
}
void ui_event_main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_flag_modify( ui_menu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_Setting_Pannel, 0);
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_main_network_panel, 0);
      _ui_opacity_set( ui_main_info_panel, 0);
      _ui_opacity_set( ui_main_win_panel, 0);
      _ui_opacity_set( ui_main_display_panel, 0);
      _ui_flag_modify( ui_message_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_backlight_setting, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      start_mqtt_recv( e );
}
}
void ui_event_win_btn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      turnmenuon_Animation(ui_menu, 0);
      passed_Animation(ui_win_btn, 0);
      _ui_flag_modify( ui_menu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_button_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      passed_Animation(ui_wifi, 0);
      passed_Animation(ui_voice, 0);
}
if ( event_code == LV_EVENT_CLICKED) {
      turnon_Animation(ui_system_ctrl_panel, 0);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_wifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      passed_Animation(ui_wifi, 0);
      passed_Animation(ui_voice, 0);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_voice( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      passed_Animation(ui_voice, 0);
      passed_Animation(ui_wifi, 0);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_sys_display_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      fadein_Animation(ui_main_display_panel, 0);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_main_info_panel, 0);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_opacity_set( ui_main_network_panel, 0);
      _ui_opacity_set( ui_main_win_panel, 0);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      clean_resources( e );
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_label_set_property(ui_panel_name, _UI_LABEL_PROPERTY_TEXT, "Display");
}
}
void ui_event_sys_win_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      fadein_Animation(ui_main_win_panel, 0);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_opacity_set( ui_main_info_panel, 0);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_opacity_set( ui_main_network_panel, 0);
      _ui_opacity_set( ui_main_display_panel, 0);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      clean_resources( e );
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_label_set_property(ui_panel_name, _UI_LABEL_PROPERTY_TEXT, "Window");
}
}
void ui_event_sys_network_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      fadein_Animation(ui_main_network_panel, 0);
      _ui_opacity_set( ui_main_info_panel, 0);
      _ui_opacity_set( ui_main_win_panel, 0);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_opacity_set( ui_main_display_panel, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      wifi_list_show( e );
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_label_set_property(ui_panel_name, _UI_LABEL_PROPERTY_TEXT, "Network");
}
}
void ui_event_sys_info_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      fadein_Animation(ui_main_info_panel, 0);
      _ui_opacity_set( ui_main_win_panel, 0);
      _ui_opacity_set( ui_main_network_panel, 0);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_opacity_set( ui_main_display_panel, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      clean_resources( e );
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_label_set_property(ui_panel_name, _UI_LABEL_PROPERTY_TEXT, "Debug");
}
}
void ui_event_set_backlight_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_set_backlight_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_set_backlight_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_PRESSED) {
      amplify_Animation(ui_message_panel, 0);
      _ui_flag_modify( ui_message_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_opacity_set( ui_message_panel, 0);
      _ui_flag_modify( ui_backlight_setting, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_set_resolution_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_set_resolution_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_set_resolution_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_set_monitor_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_state_modify( ui_set_monitor_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_set_monitor_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_Switch1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_monitor, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_Disk_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_Disk_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      cardin_Animation(ui_main_filesys_panel, 0);
      _ui_opacity_set( ui_main_filesys_panel, 0);
}
}
void ui_event_download_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_download_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      cardin_Animation(ui_main_filesys_panel, 0);
      _ui_opacity_set( ui_main_filesys_panel, 0);
}
}
void ui_event_desktop_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_desktop_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      cardin_Animation(ui_main_filesys_panel, 0);
      _ui_opacity_set( ui_main_filesys_panel, 0);
}
}
void ui_event_photo_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_state_modify( ui_photo_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      cardin_Animation(ui_main_filesys_panel, 0);
      _ui_opacity_set( ui_main_filesys_panel, 0);
}
}
void ui_event_main_filesys_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      fadeout_Animation(ui_main_filesys_panel, 0);
}
}
void ui_event_close( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_Setting_Pannel, 0);
      passed_Animation(ui_close, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      clean_resources( e );
}
}
void ui_event_scale( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      passed_Animation(ui_scale, 0);
      zoom_window( e );
}
}
void ui_event_hide( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_Setting_Pannel, 0);
      passed_Animation(ui_hide, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_sys_info_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_wifi_control( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      passed_Animation(ui_wifi_icon5, 0);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      openwin_Animation(ui_Setting_Pannel, 0);
      _ui_state_modify( ui_sys_network_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_opacity_set( ui_main_info_panel, 0);
      _ui_opacity_set( ui_main_win_panel, 0);
      _ui_opacity_set( ui_main_display_panel, 0);
      fadein_Animation(ui_main_network_panel, 0);
}
}
void ui_event_ble_control( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      passed_Animation(ui_ble_icon13, 0);
}
}
void ui_event_backlight_control__slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      backlight_slider_event_cb( e );
}
}
void ui_event_voice_control__slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      voice_slider_event_cb( e );
}
}
void ui_event_search_TextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard,  ui_search_TextArea);
      turnupkeyboard_Animation(ui_Keyboard, 0);
      _ui_flag_modify( ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_setting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      passed_Animation(ui_setting, 0);
      openwin_Animation(ui_Setting_Pannel, 0);
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_menu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_state_modify( ui_sys_display_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
      fadein_Animation(ui_main_display_panel, 0);
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_file( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      passed_Animation(ui_file, 0);
      openwin_Animation(ui_Setting_Pannel, 0);
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_menu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
      fadein_Animation(ui_main_win_panel, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_pc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      passed_Animation(ui_pc, 0);
      openwin_Animation(ui_Setting_Pannel, 0);
      _ui_flag_modify( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_menu, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_state_modify( ui_sys_win_panel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
      fadein_Animation(ui_main_win_panel, 0);
      _ui_flag_modify( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_Keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_get_act());
      turndown_Animation(ui_Keyboard, 0);
      _ui_flag_modify( ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_message_panel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      reduce_Animation(ui_message_panel, 0);
}
}
void ui_event_backlight_Slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      backlight_slider_event_cb( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_setup_screen_init();
ui_mqtt_Setting_screen_init();
ui_setting_param_screen_init();
ui_main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_setup);
}
