// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void turnon_Animation( lv_obj_t *TargetObject, int delay);
void passed_Animation( lv_obj_t *TargetObject, int delay);
void turndown_Animation( lv_obj_t *TargetObject, int delay);
void turnupkeyboard_Animation( lv_obj_t *TargetObject, int delay);
void scalewin_Animation( lv_obj_t *TargetObject, int delay);
void openwin_Animation( lv_obj_t *TargetObject, int delay);
void fadeout_Animation( lv_obj_t *TargetObject, int delay);
void fadein_Animation( lv_obj_t *TargetObject, int delay);
void EjectRight_Animation( lv_obj_t *TargetObject, int delay);
void EjectLeft_Animation( lv_obj_t *TargetObject, int delay);
void amplify_Animation( lv_obj_t *TargetObject, int delay);
void reduce_Animation( lv_obj_t *TargetObject, int delay);
void movetoleft_Animation( lv_obj_t *TargetObject, int delay);
void movetocenter_Animation( lv_obj_t *TargetObject, int delay);
void topon_Animation( lv_obj_t *TargetObject, int delay);
void topoff_Animation( lv_obj_t *TargetObject, int delay);
void lefton_Animation( lv_obj_t *TargetObject, int delay);
void leftoff_Animation( lv_obj_t *TargetObject, int delay);
void cardin_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_setup
void ui_setup_screen_init(void);
void ui_event_setup( lv_event_t * e);
extern lv_obj_t *ui_setup;
extern lv_obj_t *ui_header_group1;
extern lv_obj_t *ui_wizard_group1;
extern lv_obj_t *ui_dot3;
extern lv_obj_t *ui_line2;
extern lv_obj_t *ui_dot4;
extern lv_obj_t *ui_line4;
extern lv_obj_t *ui_dot6;
extern lv_obj_t *ui_wifi_group;
extern lv_obj_t *ui_wlan_image;
extern lv_obj_t *ui_wifi_Spinner;
extern lv_obj_t *ui_Network_panel;
extern lv_obj_t *ui_wifi_input_panel;
void ui_event_wifiTextArea( lv_event_t * e);
extern lv_obj_t *ui_wifiTextArea;
void ui_event_cancel_btn( lv_event_t * e);
extern lv_obj_t *ui_cancel_btn;
extern lv_obj_t *ui_Label12;
void ui_event_cancel_btn1( lv_event_t * e);
extern lv_obj_t *ui_cancel_btn1;
extern lv_obj_t *ui_Label13;
void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
// SCREEN: ui_mqtt_Setting
void ui_mqtt_Setting_screen_init(void);
void ui_event_mqtt_Setting( lv_event_t * e);
extern lv_obj_t *ui_mqtt_Setting;
extern lv_obj_t *ui_header_group2;
extern lv_obj_t *ui_wizard_group2;
extern lv_obj_t *ui_dot7;
extern lv_obj_t *ui_line5;
extern lv_obj_t *ui_dot8;
extern lv_obj_t *ui_line6;
extern lv_obj_t *ui_dot9;
extern lv_obj_t *ui_ok_group;
extern lv_obj_t *ui_image_ok_big1;
void ui_event_Button_Button( lv_event_t * e);
extern lv_obj_t *ui_Button;
extern lv_obj_t *ui_info_text;
extern lv_obj_t *ui_mqtt_panel;
void ui_event_subscript_text( lv_event_t * e);
extern lv_obj_t *ui_subscript_text;
void ui_event_puliish_text( lv_event_t * e);
extern lv_obj_t *ui_puliish_text;
void ui_event_clintid_text( lv_event_t * e);
extern lv_obj_t *ui_clintid_text;
void ui_event_username_text( lv_event_t * e);
extern lv_obj_t *ui_username_text;
void ui_event_password_text( lv_event_t * e);
extern lv_obj_t *ui_password_text;
void ui_event_port_text( lv_event_t * e);
extern lv_obj_t *ui_port_text;
void ui_event_Keyboard2( lv_event_t * e);
extern lv_obj_t *ui_Keyboard2;
// SCREEN: ui_setting_param
void ui_setting_param_screen_init(void);
void ui_event_setting_param( lv_event_t * e);
extern lv_obj_t *ui_setting_param;
extern lv_obj_t *ui_header_group;
extern lv_obj_t *ui_wizard_group;
extern lv_obj_t *ui_dot1;
extern lv_obj_t *ui_line1;
extern lv_obj_t *ui_dot2;
extern lv_obj_t *ui_line3;
extern lv_obj_t *ui_dot5;
extern lv_obj_t *ui_content_group;
extern lv_obj_t *ui_Label_Alarm_setting;
extern lv_obj_t *ui_footer_group;
extern lv_obj_t *ui_Roller_Temp;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_temp_roller;
extern lv_obj_t *ui_Roller_Humi;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_humi_roller;
extern lv_obj_t *ui_Label_Temp1;
extern lv_obj_t *ui_Label_Humi1;
extern lv_obj_t *ui_BTN_Choose;
void ui_event_BTN_Choose_Top( lv_event_t * e);
extern lv_obj_t *ui_BTN_Choose_Top;
extern lv_obj_t *ui_Image_Choose;
// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main( lv_event_t * e);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_wallpaper_main_img;
extern lv_obj_t *ui_Panel1;
void ui_event_win_btn( lv_event_t * e);
extern lv_obj_t *ui_win_btn;
void ui_event_button_panel( lv_event_t * e);
extern lv_obj_t *ui_button_panel;
void ui_event_wifi( lv_event_t * e);
extern lv_obj_t *ui_wifi;
void ui_event_voice( lv_event_t * e);
extern lv_obj_t *ui_voice;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_monitor;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Chart2;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Setting_Pannel;
void ui_event_sys_display_panel( lv_event_t * e);
extern lv_obj_t *ui_sys_display_panel;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label5;
void ui_event_sys_win_panel( lv_event_t * e);
extern lv_obj_t *ui_sys_win_panel;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label2;
void ui_event_sys_network_panel( lv_event_t * e);
extern lv_obj_t *ui_sys_network_panel;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label3;
void ui_event_sys_info_panel( lv_event_t * e);
extern lv_obj_t *ui_sys_info_panel;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_sys_main_panel;
extern lv_obj_t *ui_main_display_panel;
void ui_event_set_backlight_panel( lv_event_t * e);
extern lv_obj_t *ui_set_backlight_panel;
extern lv_obj_t *ui_backlight_text;
extern lv_obj_t *ui_img_right2;
void ui_event_set_resolution_panel( lv_event_t * e);
extern lv_obj_t *ui_set_resolution_panel;
extern lv_obj_t *ui_backlight_text1;
extern lv_obj_t *ui_Dropdown1;
void ui_event_set_monitor_panel( lv_event_t * e);
extern lv_obj_t *ui_set_monitor_panel;
extern lv_obj_t *ui_monitor_text;
void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_main_win_panel;
void ui_event_Disk_panel( lv_event_t * e);
extern lv_obj_t *ui_Disk_panel;
extern lv_obj_t *ui_disk_letter;
extern lv_obj_t *ui_disk_img;
extern lv_obj_t *ui_disk_free_img;
extern lv_obj_t *ui_disk_storge_text;
void ui_event_download_panel( lv_event_t * e);
extern lv_obj_t *ui_download_panel;
extern lv_obj_t *ui_download_img;
extern lv_obj_t *ui_download_letter1;
extern lv_obj_t *ui_fixation;
void ui_event_desktop_panel( lv_event_t * e);
extern lv_obj_t *ui_desktop_panel;
extern lv_obj_t *ui_desktop_img;
extern lv_obj_t *ui_desktop_letter1;
extern lv_obj_t *ui_fixation1;
void ui_event_photo_panel( lv_event_t * e);
extern lv_obj_t *ui_photo_panel;
extern lv_obj_t *ui_desktop_img1;
extern lv_obj_t *ui_photo_letter1;
extern lv_obj_t *ui_fixation2;
void ui_event_main_filesys_panel( lv_event_t * e);
extern lv_obj_t *ui_main_filesys_panel;
extern lv_obj_t *ui_main_network_panel;
extern lv_obj_t *ui_main_info_panel;
extern lv_obj_t *ui_debugArea;
extern lv_obj_t *ui_back_panel;
void ui_event_close( lv_event_t * e);
extern lv_obj_t *ui_close;
void ui_event_scale( lv_event_t * e);
extern lv_obj_t *ui_scale;
void ui_event_hide( lv_event_t * e);
extern lv_obj_t *ui_hide;
extern lv_obj_t *ui_Head;
extern lv_obj_t *ui_name;
extern lv_obj_t *ui_panel_name;
extern lv_obj_t *ui_system_ctrl_panel;
void ui_event_wifi_control( lv_event_t * e);
extern lv_obj_t *ui_wifi_control;
extern lv_obj_t *ui_wifi_icon5;
extern lv_obj_t *ui_wifi_icon6;
extern lv_obj_t *ui_midline;
void ui_event_ble_control( lv_event_t * e);
extern lv_obj_t *ui_ble_control;
extern lv_obj_t *ui_ble_icon13;
extern lv_obj_t *ui_wifi_icon2;
extern lv_obj_t *ui_midline1;
extern lv_obj_t *ui_battery_control;
extern lv_obj_t *ui_ble_icon1;
extern lv_obj_t *ui_wifi_icon3;
extern lv_obj_t *ui_midline2;
extern lv_obj_t *ui_mode_control;
extern lv_obj_t *ui_ble_icon2;
extern lv_obj_t *ui_wifi_icon4;
extern lv_obj_t *ui_midline3;
void ui_event_backlight_control__slider( lv_event_t * e);
extern lv_obj_t *ui_backlight_control__slider;
void ui_event_voice_control__slider( lv_event_t * e);
extern lv_obj_t *ui_voice_control__slider;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_menu;
void ui_event_search_TextArea( lv_event_t * e);
extern lv_obj_t *ui_search_TextArea;
extern lv_obj_t *ui_search_img;
void ui_event_setting( lv_event_t * e);
extern lv_obj_t *ui_setting;
void ui_event_file( lv_event_t * e);
extern lv_obj_t *ui_file;
void ui_event_pc( lv_event_t * e);
extern lv_obj_t *ui_pc;
void ui_event_Keyboard( lv_event_t * e);
extern lv_obj_t *ui_Keyboard;
void ui_event_message_panel( lv_event_t * e);
extern lv_obj_t *ui_message_panel;
extern lv_obj_t *ui_backlight_setting;
void ui_event_backlight_Slider( lv_event_t * e);
extern lv_obj_t *ui_backlight_Slider;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ok_small_png);   // assets\ok_small.png
LV_IMG_DECLARE( ui_img_no_signal_png);   // assets\no_signal.png
LV_IMG_DECLARE( ui_img_ok_big_png);   // assets\ok_big.png
LV_IMG_DECLARE( ui_img_btn1_png);   // assets\btn1.png
LV_IMG_DECLARE( ui_img_btn1_press_png);   // assets\btn1_press.png
LV_IMG_DECLARE( ui_img_roller_bg_png);   // assets\roller_bg.png
LV_IMG_DECLARE( ui_img_btn_print_down_png);   // assets\btn_print_down.png
LV_IMG_DECLARE( ui_img_btn_print_top_off_png);   // assets\btn_print_top_off.png
LV_IMG_DECLARE( ui_img_sure_png);   // assets\sure.png
LV_IMG_DECLARE( ui_img_bg1_png);   // assets\bg1.png
LV_IMG_DECLARE( ui_img_win_png);   // assets\win.png
LV_IMG_DECLARE( ui_img_wifi_15_png);   // assets\wifi_15.png
LV_IMG_DECLARE( ui_img_voice_png);   // assets\voice.png
LV_IMG_DECLARE( ui_img_temp_png);   // assets\temp.png
LV_IMG_DECLARE( ui_img_humi_png);   // assets\humi.png
LV_IMG_DECLARE( ui_img_display_png);   // assets\display.png
LV_IMG_DECLARE( ui_img_pc_png);   // assets\pc.png
LV_IMG_DECLARE( ui_img_network_png);   // assets\network.png
LV_IMG_DECLARE( ui_img_info_png);   // assets\info.png
LV_IMG_DECLARE( ui_img_right_png);   // assets\right.png
LV_IMG_DECLARE( ui_img_disk_png);   // assets\Disk.png
LV_IMG_DECLARE( ui_img_disk_storge_png);   // assets\disk_storge.png
LV_IMG_DECLARE( ui_img_forder_png);   // assets\forder.png
LV_IMG_DECLARE( ui_img_fixation_png);   // assets\fixation.png
LV_IMG_DECLARE( ui_img_desktop_png);   // assets\desktop.png
LV_IMG_DECLARE( ui_img_photo_icon_png);   // assets\photo_icon.png
LV_IMG_DECLARE( ui_img_close_png);   // assets\close.png
LV_IMG_DECLARE( ui_img_scale_png);   // assets\Scale.png
LV_IMG_DECLARE( ui_img_hide_png);   // assets\hide.png
LV_IMG_DECLARE( ui_img_head_png);   // assets\head.png
LV_IMG_DECLARE( ui_img_wifi_13_png);   // assets\wifi_13.png
LV_IMG_DECLARE( ui_img_ble_png);   // assets\ble.png
LV_IMG_DECLARE( ui_img_battary_png);   // assets\battary.png
LV_IMG_DECLARE( ui_img_plane_png);   // assets\plane.png
LV_IMG_DECLARE( ui_img_knob_png);   // assets\knob.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets\sun.png
LV_IMG_DECLARE( ui_img_speaker_png);   // assets\speaker.png
LV_IMG_DECLARE( ui_img_search_png);   // assets\search.png
LV_IMG_DECLARE( ui_img_setting_png);   // assets\setting.png
LV_IMG_DECLARE( ui_img_file_png);   // assets\file.png
LV_IMG_DECLARE( ui_img_pc_big_png);   // assets\pc_big.png
LV_IMG_DECLARE( ui_img_slider_bg_mario_png);   // assets\slider_bg_mario.png
LV_IMG_DECLARE( ui_img_suppermario_png);   // assets\supperMario.png
LV_IMG_DECLARE( ui_img_amplify_png);   // assets\amplify.png
LV_IMG_DECLARE( ui_img_clash_png);   // assets\clash.png
LV_IMG_DECLARE( ui_img_file_25x25_png);   // assets\file_25x25.png
LV_IMG_DECLARE( ui_img_line_png);   // assets\line.png
LV_IMG_DECLARE( ui_img_link_png);   // assets\link.png
LV_IMG_DECLARE( ui_img_position_png);   // assets\position.png
LV_IMG_DECLARE( ui_img_talk_png);   // assets\talk.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets\wifi.png
LV_IMG_DECLARE( ui_img_wifi_connect_png);   // assets\wifi_connect.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
