// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void scan_wifi_func(lv_event_t * e);
void connect_wifi_event(lv_event_t * e);
void set_mqtt_param_func(lv_event_t * e);
void show_text_sync(lv_event_t * e);
void get_keyboard_value(lv_event_t * e);
void save_alarm_parameter(lv_event_t * e);
void zoom_window(lv_event_t * e);
void backlight_slider_event_cb(lv_event_t * e);
void voice_slider_event_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
