from building import *
import os

cwd = GetCurrentDir()
group = []
src = Glob('*.c')
CPPPATH = [cwd]

group = group + DefineGroup('win32-demo', src, depend = [ 'BSP_USING_LVGL_WIN32_DEMO' ], CPPPATH = CPPPATH)

Return('group')
