// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_HOOK_H
#define _SQUARELINE_PROJECT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_button_pause2_create_hook( lv_obj_t *comp );
void ui_comp_buttonround1_create_hook( lv_obj_t *comp );
void ui_comp_settingbtn_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
