// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_button_pause2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_buttonround1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_settingbtn_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Button_create_hook( lv_obj_t * comp)
{
}

void ui_comp_dot_create_hook( lv_obj_t * comp)
{
}
