// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Button

lv_obj_t *ui_Button_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button;
cui_Button = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Button, 117);
lv_obj_set_height( cui_Button, 50);
lv_obj_set_align( cui_Button, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( cui_Button, &ui_img_btn1_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(cui_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( cui_Button, &ui_img_btn1_press_png, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_color(cui_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(cui_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t *cui_Label1;
cui_Label1 = lv_label_create(cui_Button);
lv_obj_set_width( cui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Label1, 0 );
lv_obj_set_y( cui_Label1, -7 );
lv_obj_set_align( cui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label1,"Next step");
lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_NUM);
children[UI_COMP_BUTTON_BUTTON] = cui_Button;
children[UI_COMP_BUTTON_LABEL1] = cui_Label1;
lv_obj_add_event_cb(cui_Button, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Button_create_hook(cui_Button);
return cui_Button; 
}

