// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_SETTINGBTN_H
#define _UI_COMP_SETTINGBTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT settingbtn
#define UI_COMP_SETTINGBTN_SETTINGBTN 0
#define _UI_COMP_SETTINGBTN_NUM 1
lv_obj_t *ui_settingbtn_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
