// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT button pause2

lv_obj_t *ui_button_pause2_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_button_pause2;
cui_button_pause2 = lv_btn_create(comp_parent);
lv_obj_set_width( cui_button_pause2, 45);
lv_obj_set_height( cui_button_pause2, 45);
lv_obj_set_x( cui_button_pause2, -50 );
lv_obj_set_y( cui_button_pause2, 5 );
lv_obj_set_align( cui_button_pause2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_button_pause2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_button_pause2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_button_pause2, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_button_pause2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_button_pause2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( cui_button_pause2, &ui_img_previous__png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(cui_button_pause2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(cui_button_pause2, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(cui_button_pause2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(cui_button_pause2, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(cui_button_pause2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(cui_button_pause2, 50, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(cui_button_pause2, 2, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_PAUSE2_NUM);
children[UI_COMP_BUTTON_PAUSE2_BUTTON_PAUSE2] = cui_button_pause2;
lv_obj_add_event_cb(cui_button_pause2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_button_pause2, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_button_pause2_create_hook(cui_button_pause2);
return cui_button_pause2; 
}

