// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_main, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wallpaper_main_img = lv_img_create(ui_main);
lv_img_set_src(ui_wallpaper_main_img, &ui_img_bg1_png);
lv_obj_set_width( ui_wallpaper_main_img, lv_pct(100));
lv_obj_set_height( ui_wallpaper_main_img, lv_pct(100));
lv_obj_set_align( ui_wallpaper_main_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wallpaper_main_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wallpaper_main_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wallpaper_main_img, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wallpaper_main_img, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_main);
lv_obj_set_height( ui_Panel1, 32);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_align( ui_Panel1, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 220, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_win_btn = lv_img_create(ui_Panel1);
lv_img_set_src(ui_win_btn, &ui_img_win_png);
lv_obj_set_width( ui_win_btn, 25);
lv_obj_set_height( ui_win_btn, 25);
lv_obj_set_x( ui_win_btn, -5 );
lv_obj_set_y( ui_win_btn, 0 );
lv_obj_set_align( ui_win_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_win_btn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_win_btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_button_panel = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_button_panel, 80);
lv_obj_set_height( ui_button_panel, 25);
lv_obj_set_x( ui_button_panel, 10 );
lv_obj_set_y( ui_button_panel, 0 );
lv_obj_set_align( ui_button_panel, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_button_panel, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_button_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_button_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_button_panel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_button_panel, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_button_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_button_panel, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_button_panel, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_button_panel, lv_color_hex(0x171717), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_button_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);

ui_wifi = lv_img_create(ui_button_panel);
lv_img_set_src(ui_wifi, &ui_img_wifi_15_png);
lv_obj_set_width( ui_wifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi, -15 );
lv_obj_set_y( ui_wifi, 0 );
lv_obj_set_align( ui_wifi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_voice = lv_img_create(ui_button_panel);
lv_img_set_src(ui_voice, &ui_img_voice_png);
lv_obj_set_width( ui_voice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_voice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_voice, 15 );
lv_obj_set_y( ui_voice, -1 );
lv_obj_set_align( ui_voice, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_voice, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_voice, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_time = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_time, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_time,"00:00");
lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_monitor = lv_obj_create(ui_main);
lv_obj_set_width( ui_monitor, 150);
lv_obj_set_height( ui_monitor, 240);
lv_obj_add_flag( ui_monitor, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_monitor, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_monitor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_monitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_monitor, 220, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_monitor, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_monitor);
lv_obj_set_width( ui_Arc1, 42);
lv_obj_set_height( ui_Arc1, 42);
lv_obj_set_x( ui_Arc1, 0 );
lv_obj_set_y( ui_Arc1, 5 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_Arc1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc1, -1);
lv_arc_set_bg_angles(ui_Arc1,0,360);
lv_obj_set_style_radius(ui_Arc1, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Arc1, lv_color_hex(0x14A7DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Arc1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Arc1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Arc1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_blend_mode(ui_Arc1, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Arc1);
lv_img_set_src(ui_Image7, &ui_img_temp_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc2 = lv_arc_create(ui_monitor);
lv_obj_set_width( ui_Arc2, 42);
lv_obj_set_height( ui_Arc2, 42);
lv_obj_set_x( ui_Arc2, 0 );
lv_obj_set_y( ui_Arc2, 5 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_Arc2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc2, -1);
lv_arc_set_bg_angles(ui_Arc2,0,360);
lv_obj_set_style_radius(ui_Arc2, 80, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Arc2, lv_color_hex(0x14A7DB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Arc2, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Arc2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Arc2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_blend_mode(ui_Arc2, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFBC72C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Arc2);
lv_img_set_src(ui_Image8, &ui_img_humi_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_monitor);
lv_obj_set_width( ui_Chart1, 140);
lv_obj_set_height( ui_Chart1, 30);
lv_obj_set_x( ui_Chart1, 0 );
lv_obj_set_y( ui_Chart1, -30 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 20);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFDFE7C), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 20,25,30,35,40,30,30,32,31,25,25,25,20,30,32,30 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
lv_chart_series_t* ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x00AECD), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Chart1_series_2_array[] = { 0,10,20,40,80,80,40,20,10,0,10,15,20,25,30,25,22 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Chart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_Chart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_Chart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Chart2 = lv_chart_create(ui_monitor);
lv_obj_set_width( ui_Chart2, 140);
lv_obj_set_height( ui_Chart2, 30);
lv_obj_set_x( ui_Chart2, 0 );
lv_obj_set_y( ui_Chart2, 30 );
lv_obj_set_align( ui_Chart2, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart2, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart2, 20);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xFFCB40), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart2_series_1_array[] = { 20,25,30,35,40,30,30,32,31,25,25,25,20,30,32,30 };
lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
lv_chart_series_t* ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x1690FC), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Chart2_series_2_array[] = { 0,10,20,40,80,80,40,20,10,0,10,15,20,25,30,25,22 };
lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);
lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Chart2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_Chart2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_Chart2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_Chart2, 1, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_Chart2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_monitor);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );

ui_Setting_Pannel = lv_obj_create(ui_main);
lv_obj_set_width( ui_Setting_Pannel, 450);
lv_obj_set_height( ui_Setting_Pannel, lv_pct(85));
lv_obj_set_x( ui_Setting_Pannel, 0 );
lv_obj_set_y( ui_Setting_Pannel, -14 );
lv_obj_set_align( ui_Setting_Pannel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Setting_Pannel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_set_style_radius(ui_Setting_Pannel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Setting_Pannel, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting_Pannel, 254, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Setting_Pannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Setting_Pannel, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Setting_Pannel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Setting_Pannel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Setting_Pannel, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Setting_Pannel, 5, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Setting_Pannel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_sys_display_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_height( ui_sys_display_panel, 33);
lv_obj_set_width( ui_sys_display_panel, lv_pct(29));
lv_obj_set_x( ui_sys_display_panel, -5 );
lv_obj_set_y( ui_sys_display_panel, -27 );
lv_obj_set_align( ui_sys_display_panel, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_sys_display_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_sys_display_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sys_display_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_display_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sys_display_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_sys_display_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_sys_display_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_sys_display_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_display_panel, lv_color_hex(0x636262), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_sys_display_panel, 120, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_Image4 = lv_img_create(ui_sys_display_panel);
lv_img_set_src(ui_Image4, &ui_img_display_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image4, -3 );
lv_obj_set_y( ui_Image4, 0 );
lv_obj_set_align( ui_Image4, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_sys_display_panel);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label5,"Display");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sys_win_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_height( ui_sys_win_panel, 33);
lv_obj_set_width( ui_sys_win_panel, lv_pct(29));
lv_obj_set_x( ui_sys_win_panel, -5 );
lv_obj_set_y( ui_sys_win_panel, 10 );
lv_obj_set_align( ui_sys_win_panel, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_sys_win_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_sys_win_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sys_win_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_win_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sys_win_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_sys_win_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_sys_win_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_sys_win_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_win_panel, lv_color_hex(0x636262), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_sys_win_panel, 120, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_Image1 = lv_img_create(ui_sys_win_panel);
lv_img_set_src(ui_Image1, &ui_img_pc_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -3 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_sys_win_panel);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label2,"Window");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sys_network_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_height( ui_sys_network_panel, 33);
lv_obj_set_width( ui_sys_network_panel, lv_pct(29));
lv_obj_set_x( ui_sys_network_panel, -5 );
lv_obj_set_y( ui_sys_network_panel, 48 );
lv_obj_set_align( ui_sys_network_panel, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_sys_network_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_sys_network_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sys_network_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_network_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sys_network_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_sys_network_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_network_panel, lv_color_hex(0x636262), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_sys_network_panel, 120, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_Image2 = lv_img_create(ui_sys_network_panel);
lv_img_set_src(ui_Image2, &ui_img_network_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -3 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_sys_network_panel);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label3,"Network");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sys_info_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_height( ui_sys_info_panel, 33);
lv_obj_set_width( ui_sys_info_panel, lv_pct(29));
lv_obj_set_x( ui_sys_info_panel, -5 );
lv_obj_set_y( ui_sys_info_panel, 86 );
lv_obj_set_align( ui_sys_info_panel, LV_ALIGN_LEFT_MID );
lv_obj_add_state( ui_sys_info_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_sys_info_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sys_info_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_info_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sys_info_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_sys_info_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_info_panel, lv_color_hex(0x636262), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_sys_info_panel, 120, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_Image3 = lv_img_create(ui_sys_info_panel);
lv_img_set_src(ui_Image3, &ui_img_info_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, -3 );
lv_obj_set_y( ui_Image3, 0 );
lv_obj_set_align( ui_Image3, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_sys_info_panel);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label4,"Debug");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_sys_main_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_height( ui_sys_main_panel, 145);
lv_obj_set_width( ui_sys_main_panel, lv_pct(70));
lv_obj_set_x( ui_sys_main_panel, 0 );
lv_obj_set_y( ui_sys_main_panel, 29 );
lv_obj_set_align( ui_sys_main_panel, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_sys_main_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_sys_main_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_sys_main_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_sys_main_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_sys_main_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_display_panel = lv_obj_create(ui_sys_main_panel);
lv_obj_set_width( ui_main_display_panel, 290);
lv_obj_set_height( ui_main_display_panel, 145);
lv_obj_set_align( ui_main_display_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_display_panel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_main_display_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_display_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_display_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_display_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_set_backlight_panel = lv_obj_create(ui_main_display_panel);
lv_obj_set_width( ui_set_backlight_panel, 265);
lv_obj_set_height( ui_set_backlight_panel, 30);
lv_obj_set_align( ui_set_backlight_panel, LV_ALIGN_TOP_MID );
lv_obj_add_state( ui_set_backlight_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_set_backlight_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_set_backlight_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_backlight_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_set_backlight_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_set_backlight_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_backlight_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_set_backlight_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_backlight_text = lv_label_create(ui_set_backlight_panel);
lv_obj_set_width( ui_backlight_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backlight_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backlight_text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_backlight_text,"screen backlight");
lv_obj_set_style_text_color(ui_backlight_text, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_backlight_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_backlight_text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_backlight_text, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_right2 = lv_img_create(ui_set_backlight_panel);
lv_img_set_src(ui_img_right2, &ui_img_right_png);
lv_obj_set_width( ui_img_right2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_img_right2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_img_right2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_img_right2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_right2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_set_resolution_panel = lv_obj_create(ui_main_display_panel);
lv_obj_set_width( ui_set_resolution_panel, 265);
lv_obj_set_height( ui_set_resolution_panel, 30);
lv_obj_set_x( ui_set_resolution_panel, 0 );
lv_obj_set_y( ui_set_resolution_panel, 35 );
lv_obj_set_align( ui_set_resolution_panel, LV_ALIGN_TOP_MID );
lv_obj_add_state( ui_set_resolution_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_set_resolution_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_set_resolution_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_resolution_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_set_resolution_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_set_resolution_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_resolution_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_set_resolution_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_backlight_text1 = lv_label_create(ui_set_resolution_panel);
lv_obj_set_width( ui_backlight_text1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_backlight_text1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_backlight_text1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_backlight_text1,"screen resolution");
lv_obj_set_style_text_color(ui_backlight_text1, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_backlight_text1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_backlight_text1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_backlight_text1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_set_resolution_panel);
lv_dropdown_set_options( ui_Dropdown1, "480x272\n800x480" );
lv_obj_set_width( ui_Dropdown1, 100);
lv_obj_set_height( ui_Dropdown1, 26);
lv_obj_set_x( ui_Dropdown1, 10 );
lv_obj_set_y( ui_Dropdown1, 0 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Dropdown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Dropdown1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dropdown1, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dropdown1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dropdown1, 9, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dropdown1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dropdown1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &lv_font_montserrat_10,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown1), 3,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x363636),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 190,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_dropdown_get_list(ui_Dropdown1), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x414141),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_set_monitor_panel = lv_obj_create(ui_main_display_panel);
lv_obj_set_width( ui_set_monitor_panel, 265);
lv_obj_set_height( ui_set_monitor_panel, 30);
lv_obj_set_x( ui_set_monitor_panel, 0 );
lv_obj_set_y( ui_set_monitor_panel, 70 );
lv_obj_set_align( ui_set_monitor_panel, LV_ALIGN_TOP_MID );
lv_obj_add_state( ui_set_monitor_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_set_monitor_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_set_monitor_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_monitor_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_set_monitor_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_set_monitor_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_set_monitor_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_set_monitor_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_monitor_text = lv_label_create(ui_set_monitor_panel);
lv_obj_set_width( ui_monitor_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_monitor_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_monitor_text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_monitor_text,"show monitor panel");
lv_obj_set_style_text_color(ui_monitor_text, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_monitor_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_monitor_text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_monitor_text, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch1 = lv_switch_create(ui_set_monitor_panel);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 22);
lv_obj_set_x( ui_Switch1, 9 );
lv_obj_set_y( ui_Switch1, 0 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_RIGHT_MID );


ui_main_win_panel = lv_obj_create(ui_sys_main_panel);
lv_obj_set_width( ui_main_win_panel, 290);
lv_obj_set_height( ui_main_win_panel, 145);
lv_obj_set_align( ui_main_win_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_win_panel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_main_win_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_main_win_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_win_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_win_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Disk_panel = lv_obj_create(ui_main_win_panel);
lv_obj_set_width( ui_Disk_panel, 130);
lv_obj_set_height( ui_Disk_panel, 60);
lv_obj_set_x( ui_Disk_panel, 0 );
lv_obj_set_y( ui_Disk_panel, 2 );
lv_obj_set_align( ui_Disk_panel, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_state( ui_Disk_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_Disk_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Disk_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Disk_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Disk_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Disk_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Disk_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_Disk_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_disk_letter = lv_label_create(ui_Disk_panel);
lv_obj_set_width( ui_disk_letter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_disk_letter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_disk_letter, 40 );
lv_obj_set_y( ui_disk_letter, -5 );
lv_label_set_text(ui_disk_letter,"Data(D:)");
lv_obj_set_style_text_color(ui_disk_letter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_disk_letter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_disk_letter, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_disk_letter, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_disk_img = lv_img_create(ui_Disk_panel);
lv_img_set_src(ui_disk_img, &ui_img_disk_png);
lv_obj_set_width( ui_disk_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_disk_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_disk_img, -38 );
lv_obj_set_y( ui_disk_img, 0 );
lv_obj_set_align( ui_disk_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_disk_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_disk_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_disk_free_img = lv_img_create(ui_Disk_panel);
lv_img_set_src(ui_disk_free_img, &ui_img_disk_storge_png);
lv_obj_set_width( ui_disk_free_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_disk_free_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_disk_free_img, 18 );
lv_obj_set_y( ui_disk_free_img, 3 );
lv_obj_set_align( ui_disk_free_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_disk_free_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_disk_free_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_disk_storge_text = lv_label_create(ui_Disk_panel);
lv_obj_set_width( ui_disk_storge_text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_disk_storge_text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_disk_storge_text, 15 );
lv_obj_set_y( ui_disk_storge_text, 9 );
lv_obj_set_align( ui_disk_storge_text, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_disk_storge_text,"16GB free");
lv_obj_set_style_text_color(ui_disk_storge_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_disk_storge_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_disk_storge_text, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_download_panel = lv_obj_create(ui_main_win_panel);
lv_obj_set_width( ui_download_panel, 130);
lv_obj_set_height( ui_download_panel, 60);
lv_obj_set_x( ui_download_panel, 0 );
lv_obj_set_y( ui_download_panel, -2 );
lv_obj_add_state( ui_download_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_download_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_download_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_download_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_download_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_download_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_download_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_download_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_download_img = lv_img_create(ui_download_panel);
lv_img_set_src(ui_download_img, &ui_img_forder_png);
lv_obj_set_width( ui_download_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_download_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_download_img, -38 );
lv_obj_set_y( ui_download_img, 0 );
lv_obj_set_align( ui_download_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_download_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_download_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_download_letter1 = lv_label_create(ui_download_panel);
lv_obj_set_width( ui_download_letter1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_download_letter1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_download_letter1, 40 );
lv_obj_set_y( ui_download_letter1, -5 );
lv_label_set_text(ui_download_letter1,"Download\nData(D:)");
lv_obj_set_style_text_color(ui_download_letter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_download_letter1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_download_letter1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_download_letter1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_download_letter1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_download_letter1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fixation = lv_img_create(ui_download_panel);
lv_img_set_src(ui_fixation, &ui_img_fixation_png);
lv_obj_set_width( ui_fixation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fixation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fixation, -5 );
lv_obj_set_y( ui_fixation, 6 );
lv_obj_set_align( ui_fixation, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_fixation, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_fixation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_desktop_panel = lv_obj_create(ui_main_win_panel);
lv_obj_set_width( ui_desktop_panel, 130);
lv_obj_set_height( ui_desktop_panel, 60);
lv_obj_set_x( ui_desktop_panel, 0 );
lv_obj_set_y( ui_desktop_panel, -2 );
lv_obj_set_align( ui_desktop_panel, LV_ALIGN_TOP_RIGHT );
lv_obj_add_state( ui_desktop_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_desktop_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_desktop_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_desktop_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_desktop_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_desktop_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_desktop_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_desktop_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_desktop_img = lv_img_create(ui_desktop_panel);
lv_img_set_src(ui_desktop_img, &ui_img_desktop_png);
lv_obj_set_width( ui_desktop_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_desktop_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_desktop_img, -38 );
lv_obj_set_y( ui_desktop_img, 0 );
lv_obj_set_align( ui_desktop_img, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_desktop_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_desktop_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_desktop_letter1 = lv_label_create(ui_desktop_panel);
lv_obj_set_width( ui_desktop_letter1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_desktop_letter1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_desktop_letter1, 40 );
lv_obj_set_y( ui_desktop_letter1, -5 );
lv_label_set_text(ui_desktop_letter1,"Desktop\nData(C:)");
lv_obj_set_style_text_color(ui_desktop_letter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_desktop_letter1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_desktop_letter1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_desktop_letter1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_desktop_letter1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_desktop_letter1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fixation1 = lv_img_create(ui_desktop_panel);
lv_img_set_src(ui_fixation1, &ui_img_fixation_png);
lv_obj_set_width( ui_fixation1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fixation1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fixation1, -5 );
lv_obj_set_y( ui_fixation1, 6 );
lv_obj_set_align( ui_fixation1, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_fixation1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_fixation1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_photo_panel = lv_obj_create(ui_main_win_panel);
lv_obj_set_width( ui_photo_panel, 130);
lv_obj_set_height( ui_photo_panel, 60);
lv_obj_set_x( ui_photo_panel, 0 );
lv_obj_set_y( ui_photo_panel, 2 );
lv_obj_set_align( ui_photo_panel, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_state( ui_photo_panel, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_photo_panel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_photo_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_photo_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_photo_panel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_photo_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_photo_panel, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_photo_panel, 240, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUSED);

ui_desktop_img1 = lv_img_create(ui_photo_panel);
lv_img_set_src(ui_desktop_img1, &ui_img_photo_icon_png);
lv_obj_set_width( ui_desktop_img1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_desktop_img1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_desktop_img1, -38 );
lv_obj_set_y( ui_desktop_img1, 0 );
lv_obj_set_align( ui_desktop_img1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_desktop_img1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_desktop_img1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_photo_letter1 = lv_label_create(ui_photo_panel);
lv_obj_set_width( ui_photo_letter1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_photo_letter1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_photo_letter1, 40 );
lv_obj_set_y( ui_photo_letter1, -5 );
lv_label_set_text(ui_photo_letter1,"Photo\nData(D:)");
lv_obj_set_style_text_color(ui_photo_letter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_photo_letter1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_photo_letter1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_photo_letter1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_photo_letter1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_photo_letter1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fixation2 = lv_img_create(ui_photo_panel);
lv_img_set_src(ui_fixation2, &ui_img_fixation_png);
lv_obj_set_width( ui_fixation2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fixation2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fixation2, -5 );
lv_obj_set_y( ui_fixation2, 6 );
lv_obj_set_align( ui_fixation2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_fixation2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_fixation2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_main_filesys_panel = lv_obj_create(ui_main_win_panel);
lv_obj_set_width( ui_main_filesys_panel, 290);
lv_obj_set_height( ui_main_filesys_panel, 145);
lv_obj_set_align( ui_main_filesys_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_filesys_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_main_filesys_panel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_main_filesys_panel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_main_filesys_panel, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_filesys_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_filesys_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_network_panel = lv_obj_create(ui_sys_main_panel);
lv_obj_set_width( ui_main_network_panel, 290);
lv_obj_set_height( ui_main_network_panel, 145);
lv_obj_set_align( ui_main_network_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_network_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_main_network_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_network_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_network_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_main_info_panel = lv_obj_create(ui_sys_main_panel);
lv_obj_set_width( ui_main_info_panel, 290);
lv_obj_set_height( ui_main_info_panel, 145);
lv_obj_set_align( ui_main_info_panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_main_info_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_main_info_panel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_radius(ui_main_info_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_main_info_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_main_info_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_main_info_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_debugArea = lv_textarea_create(ui_main_info_panel);
lv_obj_set_width( ui_debugArea, 280);
lv_obj_set_height( ui_debugArea, 135);
lv_obj_set_align( ui_debugArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_debugArea,"Received network data");
lv_obj_clear_flag( ui_debugArea, LV_OBJ_FLAG_CLICKABLE );    /// Flags



ui_back_panel = lv_obj_create(ui_Setting_Pannel);
lv_obj_set_width( ui_back_panel, 86);
lv_obj_set_height( ui_back_panel, 25);
lv_obj_set_x( ui_back_panel, 0 );
lv_obj_set_y( ui_back_panel, -10 );
lv_obj_set_align( ui_back_panel, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_back_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back_panel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_back_panel, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_back_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_back_panel, 150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_close = lv_img_create(ui_back_panel);
lv_img_set_src(ui_close, &ui_img_close_png);
lv_obj_set_width( ui_close, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_close, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_close, 7 );
lv_obj_set_y( ui_close, 0 );
lv_obj_set_align( ui_close, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_close, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_close, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_scale = lv_img_create(ui_back_panel);
lv_img_set_src(ui_scale, &ui_img_scale_png);
lv_obj_set_width( ui_scale, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_scale, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_scale, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_scale, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_scale, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_hide = lv_img_create(ui_back_panel);
lv_img_set_src(ui_hide, &ui_img_hide_png);
lv_obj_set_width( ui_hide, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hide, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hide, -7 );
lv_obj_set_y( ui_hide, 0 );
lv_obj_set_align( ui_hide, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_hide, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_hide, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Head = lv_img_create(ui_Setting_Pannel);
lv_img_set_src(ui_Head, &ui_img_head_png);
lv_obj_set_width( ui_Head, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Head, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Head, -1 );
lv_obj_set_y( ui_Head, -8 );
lv_obj_add_flag( ui_Head, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Head, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_name = lv_label_create(ui_Setting_Pannel);
lv_obj_set_width( ui_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_name, 45 );
lv_obj_set_y( ui_name, 2 );
lv_label_set_text(ui_name,"User\nLVGL&RTT");
lv_obj_set_style_text_color(ui_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_name, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_name, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_name, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel_name = lv_label_create(ui_Setting_Pannel);
lv_obj_set_width( ui_panel_name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel_name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel_name, -55 );
lv_obj_set_y( ui_panel_name, 2 );
lv_obj_set_align( ui_panel_name, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_panel_name,"Display");
lv_obj_set_style_text_color(ui_panel_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel_name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_panel_name, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel_name, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_system_ctrl_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_system_ctrl_panel, 125);
lv_obj_set_height( ui_system_ctrl_panel, 138);
lv_obj_set_x( ui_system_ctrl_panel, -2 );
lv_obj_set_y( ui_system_ctrl_panel, -34 );
lv_obj_set_align( ui_system_ctrl_panel, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_system_ctrl_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_system_ctrl_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_system_ctrl_panel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_system_ctrl_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_system_ctrl_panel, 230, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_system_ctrl_panel, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_system_ctrl_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_system_ctrl_panel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi_control = lv_obj_create(ui_system_ctrl_panel);
lv_obj_set_width( ui_wifi_control, 50);
lv_obj_set_height( ui_wifi_control, 28);
lv_obj_set_x( ui_wifi_control, -3 );
lv_obj_set_y( ui_wifi_control, -4 );
lv_obj_clear_flag( ui_wifi_control, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifi_control, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifi_control, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi_control, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_wifi_control, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_wifi_control, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifi_control, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifi_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_wifi_control, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_wifi_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_wifi_control, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_wifi_icon5 = lv_img_create(ui_wifi_control);
lv_img_set_src(ui_wifi_icon5, &ui_img_wifi_13_png);
lv_obj_set_width( ui_wifi_icon5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_icon5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_icon5, -6 );
lv_obj_set_y( ui_wifi_icon5, 0 );
lv_obj_set_align( ui_wifi_icon5, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_wifi_icon5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_icon5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_icon6 = lv_img_create(ui_wifi_control);
lv_img_set_src(ui_wifi_icon6, &ui_img_right_png);
lv_obj_set_width( ui_wifi_icon6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_icon6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_icon6, 8 );
lv_obj_set_y( ui_wifi_icon6, 1 );
lv_obj_set_align( ui_wifi_icon6, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_wifi_icon6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_icon6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_midline = lv_obj_create(ui_wifi_control);
lv_obj_set_width( ui_midline, 1);
lv_obj_set_height( ui_midline, 30);
lv_obj_set_align( ui_midline, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_midline, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_midline, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_midline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ble_control = lv_obj_create(ui_system_ctrl_panel);
lv_obj_set_width( ui_ble_control, 50);
lv_obj_set_height( ui_ble_control, 28);
lv_obj_set_x( ui_ble_control, 3 );
lv_obj_set_y( ui_ble_control, -4 );
lv_obj_set_align( ui_ble_control, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ble_control, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_ble_control, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ble_control, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ble_control, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ble_control, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ble_control, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ble_control, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ble_control, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ble_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ble_control, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ble_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ble_control, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ble_icon13 = lv_img_create(ui_ble_control);
lv_img_set_src(ui_ble_icon13, &ui_img_ble_png);
lv_obj_set_width( ui_ble_icon13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ble_icon13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ble_icon13, -6 );
lv_obj_set_y( ui_ble_icon13, 0 );
lv_obj_set_align( ui_ble_icon13, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ble_icon13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ble_icon13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_icon2 = lv_img_create(ui_ble_control);
lv_img_set_src(ui_wifi_icon2, &ui_img_right_png);
lv_obj_set_width( ui_wifi_icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_icon2, 8 );
lv_obj_set_y( ui_wifi_icon2, 1 );
lv_obj_set_align( ui_wifi_icon2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_wifi_icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_midline1 = lv_obj_create(ui_ble_control);
lv_obj_set_width( ui_midline1, 1);
lv_obj_set_height( ui_midline1, 30);
lv_obj_set_align( ui_midline1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_midline1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_midline1, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_midline1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battery_control = lv_obj_create(ui_system_ctrl_panel);
lv_obj_set_width( ui_battery_control, 50);
lv_obj_set_height( ui_battery_control, 28);
lv_obj_set_x( ui_battery_control, -3 );
lv_obj_set_y( ui_battery_control, -8 );
lv_obj_set_align( ui_battery_control, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_battery_control, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_battery_control, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_battery_control, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_battery_control, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_battery_control, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_battery_control, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_battery_control, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_battery_control, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_battery_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_battery_control, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_battery_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_battery_control, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ble_icon1 = lv_img_create(ui_battery_control);
lv_img_set_src(ui_ble_icon1, &ui_img_battary_png);
lv_obj_set_width( ui_ble_icon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ble_icon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ble_icon1, -6 );
lv_obj_set_y( ui_ble_icon1, 0 );
lv_obj_set_align( ui_ble_icon1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ble_icon1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ble_icon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_icon3 = lv_img_create(ui_battery_control);
lv_img_set_src(ui_wifi_icon3, &ui_img_right_png);
lv_obj_set_width( ui_wifi_icon3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_icon3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_icon3, 8 );
lv_obj_set_y( ui_wifi_icon3, 1 );
lv_obj_set_align( ui_wifi_icon3, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_wifi_icon3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_icon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_midline2 = lv_obj_create(ui_battery_control);
lv_obj_set_width( ui_midline2, 1);
lv_obj_set_height( ui_midline2, 30);
lv_obj_set_align( ui_midline2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_midline2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_midline2, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_midline2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mode_control = lv_obj_create(ui_system_ctrl_panel);
lv_obj_set_width( ui_mode_control, 50);
lv_obj_set_height( ui_mode_control, 28);
lv_obj_set_x( ui_mode_control, 3 );
lv_obj_set_y( ui_mode_control, -8 );
lv_obj_set_align( ui_mode_control, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_mode_control, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_mode_control, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mode_control, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mode_control, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mode_control, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mode_control, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mode_control, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mode_control, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mode_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_mode_control, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_mode_control, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_mode_control, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ble_icon2 = lv_img_create(ui_mode_control);
lv_img_set_src(ui_ble_icon2, &ui_img_plane_png);
lv_obj_set_width( ui_ble_icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ble_icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ble_icon2, -6 );
lv_obj_set_y( ui_ble_icon2, 0 );
lv_obj_set_align( ui_ble_icon2, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ble_icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ble_icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifi_icon4 = lv_img_create(ui_mode_control);
lv_img_set_src(ui_wifi_icon4, &ui_img_right_png);
lv_obj_set_width( ui_wifi_icon4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_icon4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi_icon4, 8 );
lv_obj_set_y( ui_wifi_icon4, 1 );
lv_obj_set_align( ui_wifi_icon4, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_wifi_icon4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_icon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_midline3 = lv_obj_create(ui_mode_control);
lv_obj_set_width( ui_midline3, 1);
lv_obj_set_height( ui_midline3, 30);
lv_obj_set_align( ui_midline3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_midline3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_midline3, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_midline3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backlight_control__slider = lv_slider_create(ui_system_ctrl_panel);
lv_slider_set_value( ui_backlight_control__slider, 70, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_backlight_control__slider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_backlight_control__slider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_backlight_control__slider, 85);
lv_obj_set_height( ui_backlight_control__slider, 4);
lv_obj_set_x( ui_backlight_control__slider, 10 );
lv_obj_set_y( ui_backlight_control__slider, -26 );
lv_obj_set_align( ui_backlight_control__slider, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_backlight_control__slider, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_control__slider, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_backlight_control__slider, lv_color_hex(0xD59EDE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_control__slider, 220, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_backlight_control__slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_control__slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_backlight_control__slider, &ui_img_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT );

ui_voice_control__slider = lv_slider_create(ui_system_ctrl_panel);
lv_slider_set_range(ui_voice_control__slider, -16,16);
lv_obj_set_width( ui_voice_control__slider, 85);
lv_obj_set_height( ui_voice_control__slider, 4);
lv_obj_set_x( ui_voice_control__slider, 10 );
lv_obj_set_y( ui_voice_control__slider, -3 );
lv_obj_set_align( ui_voice_control__slider, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_bg_color(ui_voice_control__slider, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_voice_control__slider, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_voice_control__slider, lv_color_hex(0xD59EDE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_voice_control__slider, 220, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_voice_control__slider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_voice_control__slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_voice_control__slider, &ui_img_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT );

ui_Image5 = lv_img_create(ui_system_ctrl_panel);
lv_img_set_src(ui_Image5, &ui_img_sun_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, -88 );
lv_obj_set_y( ui_Image5, -21 );
lv_obj_set_align( ui_Image5, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_system_ctrl_panel);
lv_img_set_src(ui_Image6, &ui_img_speaker_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, -87 );
lv_obj_set_y( ui_Image6, 2 );
lv_obj_set_align( ui_Image6, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_menu = lv_obj_create(ui_main);
lv_obj_set_width( ui_menu, 160);
lv_obj_set_height( ui_menu, 85);
lv_obj_set_x( ui_menu, 0 );
lv_obj_set_y( ui_menu, 55 );
lv_obj_set_align( ui_menu, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_menu, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_scrollbar_mode(ui_menu, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_bg_color(ui_menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_menu, 220, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menu, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_menu, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_menu, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_menu, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_menu, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_search_TextArea = lv_textarea_create(ui_menu);
lv_obj_set_width( ui_search_TextArea, 140);
lv_obj_set_height( ui_search_TextArea, 15);
lv_obj_set_x( ui_search_TextArea, 0 );
lv_obj_set_y( ui_search_TextArea, -28 );
lv_obj_set_align( ui_search_TextArea, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_search_TextArea,"            Search");
lv_obj_clear_flag( ui_search_TextArea, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_color(ui_search_TextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_search_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_search_TextArea, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_search_TextArea, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_search_TextArea, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_search_TextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_search_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_search_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_search_TextArea, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_search_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_search_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_search_TextArea, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_search_TextArea, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_search_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_search_TextArea, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_search_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_text_color(ui_search_TextArea, lv_color_hex(0x9C9C9C), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_search_TextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_search_TextArea, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_search_TextArea, LV_TEXT_DECOR_NONE, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_search_TextArea, &lv_font_montserrat_10, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_search_img = lv_img_create(ui_search_TextArea);
lv_img_set_src(ui_search_img, &ui_img_search_png);
lv_obj_set_width( ui_search_img, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_search_img, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_search_img, -10 );
lv_obj_set_y( ui_search_img, 0 );
lv_obj_set_align( ui_search_img, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_search_img, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_search_img, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_setting = lv_img_create(ui_menu);
lv_img_set_src(ui_setting, &ui_img_setting_png);
lv_obj_set_width( ui_setting, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_setting, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_setting, 5 );
lv_obj_set_y( ui_setting, 0 );
lv_obj_set_align( ui_setting, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_setting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_setting, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags

ui_file = lv_img_create(ui_menu);
lv_img_set_src(ui_file, &ui_img_file_png);
lv_obj_set_width( ui_file, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_file, LV_SIZE_CONTENT);   /// 28
lv_obj_set_align( ui_file, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_file, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_file, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags

ui_pc = lv_img_create(ui_menu);
lv_img_set_src(ui_pc, &ui_img_pc_big_png);
lv_obj_set_width( ui_pc, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_pc, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_pc, -6 );
lv_obj_set_y( ui_pc, 0 );
lv_obj_set_align( ui_pc, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_pc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags

ui_Keyboard = lv_keyboard_create(ui_main);
lv_obj_set_width( ui_Keyboard, lv_pct(80));
lv_obj_set_height( ui_Keyboard, lv_pct(45));
lv_obj_set_x( ui_Keyboard, 0 );
lv_obj_set_y( ui_Keyboard, 200 );
lv_obj_set_align( ui_Keyboard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Keyboard, LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_radius(ui_Keyboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard, 190, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Keyboard, 2, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard, 200, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_message_panel = lv_obj_create(ui_main);
lv_obj_set_width( ui_message_panel, lv_pct(60));
lv_obj_set_height( ui_message_panel, lv_pct(55));
lv_obj_set_align( ui_message_panel, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_message_panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_message_panel, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_message_panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_message_panel, lv_color_hex(0x161616), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_message_panel, 245, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_message_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_message_panel, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_message_panel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backlight_setting = lv_obj_create(ui_message_panel);
lv_obj_set_width( ui_backlight_setting, lv_pct(100));
lv_obj_set_height( ui_backlight_setting, lv_pct(100));
lv_obj_set_align( ui_backlight_setting, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_backlight_setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_backlight_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_backlight_setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_backlight_Slider = lv_slider_create(ui_backlight_setting);
lv_slider_set_value( ui_backlight_Slider, 70, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_backlight_Slider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_backlight_Slider, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_backlight_Slider, 40);
lv_obj_set_width( ui_backlight_Slider, lv_pct(100));
lv_obj_set_align( ui_backlight_Slider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_backlight_Slider, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_backlight_Slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_Slider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_backlight_Slider, &ui_img_slider_bg_mario_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_backlight_Slider, lv_color_hex(0x02AFE0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_backlight_Slider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_backlight_Slider, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_backlight_Slider, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_backlight_Slider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_Slider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_backlight_Slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_backlight_Slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_backlight_Slider, &ui_img_suppermario_png, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_pad_left(ui_backlight_Slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_backlight_Slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_backlight_Slider, -8, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_backlight_Slider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_win_btn, ui_event_win_btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifi, ui_event_wifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_voice, ui_event_voice, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_button_panel, ui_event_button_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sys_display_panel, ui_event_sys_display_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sys_win_panel, ui_event_sys_win_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sys_network_panel, ui_event_sys_network_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_sys_info_panel, ui_event_sys_info_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_set_backlight_panel, ui_event_set_backlight_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_set_resolution_panel, ui_event_set_resolution_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_set_monitor_panel, ui_event_set_monitor_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Disk_panel, ui_event_Disk_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_download_panel, ui_event_download_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_desktop_panel, ui_event_desktop_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_photo_panel, ui_event_photo_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_main_filesys_panel, ui_event_main_filesys_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_close, ui_event_close, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_scale, ui_event_scale, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_hide, ui_event_hide, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifi_control, ui_event_wifi_control, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ble_control, ui_event_ble_control, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_backlight_control__slider, ui_event_backlight_control__slider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_voice_control__slider, ui_event_voice_control__slider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_search_TextArea, ui_event_search_TextArea, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_file, ui_event_file, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pc, ui_event_pc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_backlight_Slider, ui_event_backlight_Slider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_message_panel, ui_event_message_panel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}
