// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_mqtt_Setting_screen_init(void)
{
ui_mqtt_Setting = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mqtt_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mqtt_Setting, lv_color_hex(0x21212E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqtt_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_mqtt_Setting, lv_color_hex(0x2D394F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_mqtt_Setting, 175, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_mqtt_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_mqtt_Setting, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_header_group2 = lv_obj_create(ui_mqtt_Setting);
lv_obj_set_height( ui_header_group2, 50);
lv_obj_set_width( ui_header_group2, lv_pct(100));
lv_obj_set_align( ui_header_group2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_header_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_header_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wizard_group2 = lv_obj_create(ui_header_group2);
lv_obj_set_width( ui_wizard_group2, 256);
lv_obj_set_height( ui_wizard_group2, 50);
lv_obj_set_align( ui_wizard_group2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wizard_group2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wizard_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_wizard_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wizard_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wizard_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wizard_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_wizard_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wizard_group2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot7 = ui_dot_create(ui_wizard_group2);
lv_obj_set_x( ui_dot7, 0 );
lv_obj_set_y( ui_dot7, 0 );
lv_obj_clear_state( ui_dot7, LV_STATE_CHECKED );   /// States


lv_obj_clear_flag( ui_comp_get_child(ui_dot7, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN );    /// Flags

lv_obj_clear_flag( ui_comp_get_child(ui_dot7, UI_COMP_DOT_IMAGE11), LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_line5 = lv_obj_create(ui_wizard_group2);
lv_obj_set_width( ui_line5, 50);
lv_obj_set_height( ui_line5, 3);
lv_obj_set_align( ui_line5, LV_ALIGN_CENTER );
lv_obj_add_state( ui_line5, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_line5, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_line5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_line5, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_line5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_line5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_line5, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_line5, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_dot8 = ui_dot_create(ui_wizard_group2);
lv_obj_set_x( ui_dot8, 0 );
lv_obj_set_y( ui_dot8, 0 );
lv_obj_add_state( ui_dot8, LV_STATE_CHECKED );     /// States

lv_label_set_text(ui_comp_get_child(ui_dot8, UI_COMP_DOT_LABEL_DOT),"2");

lv_obj_set_style_radius(ui_comp_get_child(ui_dot8, UI_COMP_DOT_READY_BG), 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_comp_get_child(ui_dot8, UI_COMP_DOT_READY_BG), lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dot8, UI_COMP_DOT_READY_BG), 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_line6 = lv_obj_create(ui_wizard_group2);
lv_obj_set_width( ui_line6, 50);
lv_obj_set_height( ui_line6, 3);
lv_obj_set_align( ui_line6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_line6, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_line6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_line6, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_line6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_line6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_line6, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_line6, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_dot9 = ui_dot_create(ui_wizard_group2);
lv_obj_set_x( ui_dot9, 0 );
lv_obj_set_y( ui_dot9, 0 );
lv_obj_clear_state( ui_dot9, LV_STATE_CHECKED );   /// States

lv_label_set_text(ui_comp_get_child(ui_dot9, UI_COMP_DOT_LABEL_DOT),"3");



ui_ok_group = lv_obj_create(ui_mqtt_Setting);
lv_obj_set_width( ui_ok_group, 194);
lv_obj_set_height( ui_ok_group, 249);
lv_obj_set_align( ui_ok_group, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ok_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ok_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ok_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ok_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqtt_Spinner = lv_spinner_create(ui_ok_group,1000,90);
lv_obj_set_width( ui_mqtt_Spinner, 100);
lv_obj_set_height( ui_mqtt_Spinner, 100);
lv_obj_set_align( ui_mqtt_Spinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mqtt_Spinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_mqtt_Spinner, lv_color_hex(0x8F8FFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_mqtt_Spinner, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_mqtt_Spinner, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_mqtt_Spinner, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_mqtt_Spinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_mqtt_Spinner, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_mqtt_image = lv_img_create(ui_ok_group);
lv_img_set_src(ui_mqtt_image, &ui_img_no_conn_png);
lv_obj_set_width( ui_mqtt_image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqtt_image, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mqtt_image, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mqtt_image, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_mqtt_image, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button = ui_Button_create(ui_ok_group);
lv_obj_set_x( ui_Button, 0 );
lv_obj_set_y( ui_Button, 10 );

ui_info_text = lv_textarea_create(ui_ok_group);
lv_obj_set_width( ui_info_text, 129);
lv_obj_set_height( ui_info_text, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_info_text, 0 );
lv_obj_set_y( ui_info_text, 17 );
lv_obj_set_align( ui_info_text, LV_ALIGN_TOP_MID );
lv_textarea_set_one_line(ui_info_text,true);
lv_obj_clear_flag( ui_info_text, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_text_color(ui_info_text, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_info_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_info_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_info_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_info_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_mqtt_panel = lv_obj_create(ui_mqtt_Setting);
lv_obj_set_width( ui_mqtt_panel, 265);
lv_obj_set_height( ui_mqtt_panel, 195);
lv_obj_set_x( ui_mqtt_panel, -20 );
lv_obj_set_y( ui_mqtt_panel, 15 );
lv_obj_set_align( ui_mqtt_panel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_mqtt_panel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_mqtt_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_add_flag( ui_mqtt_panel, LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_set_style_bg_color(ui_mqtt_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqtt_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mqtt_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_subscript_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_subscript_text, 209);
lv_obj_set_height( ui_subscript_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_placeholder_text(ui_subscript_text,"Subscript Topic");
lv_textarea_set_one_line(ui_subscript_text,true);
lv_obj_set_style_text_color(ui_subscript_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_subscript_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_subscript_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_subscript_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_subscript_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_puliish_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_puliish_text, 209);
lv_obj_set_height( ui_puliish_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_placeholder_text(ui_puliish_text,"Publish Topic");
lv_textarea_set_one_line(ui_puliish_text,true);
lv_obj_set_style_text_color(ui_puliish_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_puliish_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_puliish_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_puliish_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_puliish_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_clintid_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_clintid_text, 209);
lv_obj_set_height( ui_clintid_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_placeholder_text(ui_clintid_text,"Clint ID");
lv_textarea_set_one_line(ui_clintid_text,true);
lv_obj_set_style_text_color(ui_clintid_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clintid_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_clintid_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clintid_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_clintid_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_clint_addr_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_clint_addr_text, 209);
lv_obj_set_height( ui_clint_addr_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_text(ui_clint_addr_text,"broker.emqx.io");
lv_textarea_set_placeholder_text(ui_clint_addr_text,"Clint addr");
lv_textarea_set_one_line(ui_clint_addr_text,true);
lv_obj_set_style_text_color(ui_clint_addr_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clint_addr_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_clint_addr_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_clint_addr_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_clint_addr_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_username_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_username_text, 209);
lv_obj_set_height( ui_username_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_text(ui_username_text,"RT-Thread");
lv_textarea_set_placeholder_text(ui_username_text,"Clint Username");
lv_textarea_set_one_line(ui_username_text,true);
lv_obj_set_style_text_color(ui_username_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_username_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_username_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_username_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_username_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_password_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_password_text, 209);
lv_obj_set_height( ui_password_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_text(ui_password_text,"012345678");
lv_textarea_set_placeholder_text(ui_password_text,"Clint Password");
lv_textarea_set_one_line(ui_password_text,true);
lv_obj_set_style_text_color(ui_password_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_password_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_password_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_password_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_password_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_port_text = lv_textarea_create(ui_mqtt_panel);
lv_obj_set_width( ui_port_text, 209);
lv_obj_set_height( ui_port_text, LV_SIZE_CONTENT);   /// 30
lv_textarea_set_text(ui_port_text,"1883");
lv_textarea_set_placeholder_text(ui_port_text,"Port");
lv_textarea_set_one_line(ui_port_text,true);
lv_obj_set_style_text_color(ui_port_text, lv_color_hex(0x789DFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_port_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_port_text, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_port_text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_port_text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Keyboard2 = lv_keyboard_create(ui_mqtt_Setting);
lv_obj_set_width( ui_Keyboard2, lv_pct(100));
lv_obj_set_height( ui_Keyboard2, lv_pct(50));
lv_obj_set_x( ui_Keyboard2, 0 );
lv_obj_set_y( ui_Keyboard2, 200 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Keyboard2, LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_style_radius(ui_Keyboard2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Keyboard2, 2, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Keyboard2, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button, ui_event_Button_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_subscript_text, ui_event_subscript_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_puliish_text, ui_event_puliish_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_clintid_text, ui_event_clintid_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_clint_addr_text, ui_event_clint_addr_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_username_text, ui_event_username_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_password_text, ui_event_password_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_port_text, ui_event_port_text, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mqtt_Setting, ui_event_mqtt_Setting, LV_EVENT_ALL, NULL);

}
