// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "utils.h"
#include "sys/time.h"

#define RTC_NAME       "rtc"

struct player v_player;
static lv_timer_t *start_timer;
static lv_timer_t *video_timer;
static lv_timer_t *rtc_timer;
extern int WiFi_Scan(void);

static void start_timer_callback(lv_timer_t *timer)
{
	player_control(&v_player, PLAYER_CMD_INIT, "video/start.avi");
}

static void video_timer_callback(lv_timer_t *timer)
{
    _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
}

static void rtc_timer_callback(lv_timer_t *timer)
{
    time_t timep;
    struct tm *p;
 
    time(&timep);
    p = localtime(&timep);
	if (!lv_obj_has_flag(ui_time, LV_OBJ_FLAG_HIDDEN))
	{
		lv_label_set_text_fmt(ui_time, "%d:%d", p->tm_hour, p->tm_min);
	}
}

int setup_time(void)
{
    rt_err_t ret = RT_EOK;
    rt_device_t device = RT_NULL;

    device = rt_device_find(RTC_NAME);
    if (!device)
    {
        rt_kprintf("find %s failed!", RTC_NAME);
        return RT_ERROR;
    }

    if (rt_device_open(device, 0) != RT_EOK)
    {
        rt_kprintf("open %s failed!", RTC_NAME);
        return RT_ERROR;
    }

    ret = set_date(2023, 9, 16);
    if (ret != RT_EOK)
    {
        rt_kprintf("set RTC date failed\n");
        return ret;
    }

    ret = set_time(23, 15, 50);
    if (ret != RT_EOK)
    {
        rt_kprintf("set RTC time failed\n");
        return ret;
    }

    return ret;
}

void ui_setup_screen_init(void)
{
    ui_setup = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setup, ui_event_setup, LV_EVENT_ALL, NULL);
    player_start(&v_player);
	start_timer = lv_timer_create(start_timer_callback, 400, NULL);
    lv_timer_set_repeat_count(start_timer, 1);
    video_timer = lv_timer_create(video_timer_callback, 5500, NULL);
    lv_timer_set_repeat_count(video_timer, 1);
    WiFi_Scan();
	setup_time();
	rtc_timer = lv_timer_create(rtc_timer_callback, 5 * 1000, NULL);
}
