// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_setting_param_screen_init(void)
{
ui_setting_param = lv_obj_create(NULL);
lv_obj_clear_flag( ui_setting_param, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_setting_param,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_setting_param, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_setting_param, lv_color_hex(0x21212E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setting_param, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setting_param, lv_color_hex(0x2D394F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_setting_param, 175, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_setting_param, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_setting_param, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_header_group = lv_obj_create(ui_setting_param);
lv_obj_set_height( ui_header_group, 50);
lv_obj_set_width( ui_header_group, lv_pct(100));
lv_obj_set_align( ui_header_group, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_header_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_header_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wizard_group = lv_obj_create(ui_header_group);
lv_obj_set_width( ui_wizard_group, 256);
lv_obj_set_height( ui_wizard_group, 50);
lv_obj_set_align( ui_wizard_group, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wizard_group,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wizard_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_wizard_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wizard_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wizard_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wizard_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_wizard_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wizard_group, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot1 = ui_dot_create(ui_wizard_group);
lv_obj_set_x( ui_dot1, 0 );
lv_obj_set_y( ui_dot1, 0 );
lv_obj_clear_state( ui_dot1, LV_STATE_CHECKED );   /// States


lv_obj_clear_flag( ui_comp_get_child(ui_dot1, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN );    /// Flags

lv_obj_clear_flag( ui_comp_get_child(ui_dot1, UI_COMP_DOT_IMAGE11), LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_line1 = lv_obj_create(ui_wizard_group);
lv_obj_set_width( ui_line1, 50);
lv_obj_set_height( ui_line1, 3);
lv_obj_set_align( ui_line1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_line1, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_line1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_line1, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_line1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_line1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_line1, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_line1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_dot2 = ui_dot_create(ui_wizard_group);
lv_obj_set_x( ui_dot2, 0 );
lv_obj_set_y( ui_dot2, 0 );

lv_label_set_text(ui_comp_get_child(ui_dot2, UI_COMP_DOT_LABEL_DOT),"2");

lv_obj_clear_flag( ui_comp_get_child(ui_dot2, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN );    /// Flags

lv_obj_clear_flag( ui_comp_get_child(ui_dot2, UI_COMP_DOT_IMAGE11), LV_OBJ_FLAG_HIDDEN );    /// Flags

ui_line3 = lv_obj_create(ui_wizard_group);
lv_obj_set_width( ui_line3, 50);
lv_obj_set_height( ui_line3, 3);
lv_obj_set_align( ui_line3, LV_ALIGN_CENTER );
lv_obj_add_state( ui_line3, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_line3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_line3, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_line3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_line3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_line3, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_line3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_dot5 = ui_dot_create(ui_wizard_group);
lv_obj_set_x( ui_dot5, 0 );
lv_obj_set_y( ui_dot5, 0 );
lv_obj_add_state( ui_dot5, LV_STATE_CHECKED );     /// States

lv_label_set_text(ui_comp_get_child(ui_dot5, UI_COMP_DOT_LABEL_DOT),"3");



ui_content_group = lv_obj_create(ui_setting_param);
lv_obj_set_height( ui_content_group, 35);
lv_obj_set_width( ui_content_group, lv_pct(100));
lv_obj_set_align( ui_content_group, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_content_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_content_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_content_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_content_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Alarm_setting = lv_label_create(ui_content_group);
lv_obj_set_width( ui_Label_Alarm_setting, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Alarm_setting, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Alarm_setting, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Alarm_setting,"                    Alarm settings                   ");
lv_obj_add_flag( ui_Label_Alarm_setting, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_set_style_text_color(ui_Label_Alarm_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Alarm_setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Alarm_setting, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Alarm_setting, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label_Alarm_setting, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label_Alarm_setting, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label_Alarm_setting, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label_Alarm_setting, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Label_Alarm_setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_Label_Alarm_setting, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(ui_Label_Alarm_setting, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_radius(ui_Label_Alarm_setting, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Label_Alarm_setting, lv_color_hex(0x49AD46), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Label_Alarm_setting, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_footer_group = lv_obj_create(ui_setting_param);
lv_obj_set_height( ui_footer_group, 142);
lv_obj_set_width( ui_footer_group, lv_pct(100));
lv_obj_set_x( ui_footer_group, 8 );
lv_obj_set_y( ui_footer_group, 72 );
lv_obj_set_align( ui_footer_group, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_footer_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_footer_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_footer_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_footer_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller_Temp = lv_obj_create(ui_footer_group);
lv_obj_set_height( ui_Roller_Temp, 124);
lv_obj_set_width( ui_Roller_Temp, LV_SIZE_CONTENT);  /// 960
lv_obj_set_x( ui_Roller_Temp, 0 );
lv_obj_set_y( ui_Roller_Temp, 5 );
lv_obj_set_align( ui_Roller_Temp, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Roller_Temp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Roller_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Roller_Temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Roller_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller_Temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_Roller_Temp);
lv_img_set_src(ui_Image9, &ui_img_roller_bg_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temp_roller = lv_roller_create(ui_Roller_Temp);
lv_roller_set_options( ui_temp_roller, "40°\n50°\n55°\n60°\n65°\n70°\n70°", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_temp_roller, 91);
lv_obj_set_height( ui_temp_roller, 90);
lv_obj_set_align( ui_temp_roller, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_temp_roller, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp_roller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp_roller, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temp_roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_temp_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_temp_roller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_temp_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_temp_roller, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp_roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp_roller, &lv_font_montserrat_14, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temp_roller, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temp_roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller_Humi = lv_obj_create(ui_footer_group);
lv_obj_set_height( ui_Roller_Humi, 124);
lv_obj_set_width( ui_Roller_Humi, LV_SIZE_CONTENT);  /// 960
lv_obj_set_x( ui_Roller_Humi, 0 );
lv_obj_set_y( ui_Roller_Humi, 5 );
lv_obj_set_align( ui_Roller_Humi, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Roller_Humi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Roller_Humi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_Humi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_Roller_Humi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Roller_Humi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller_Humi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image10 = lv_img_create(ui_Roller_Humi);
lv_img_set_src(ui_Image10, &ui_img_roller_bg_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_humi_roller = lv_roller_create(ui_Roller_Humi);
lv_roller_set_options( ui_humi_roller, "20%\n30%\n45%\n50%\n65%\n70°\n70°", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_humi_roller, 91);
lv_obj_set_height( ui_humi_roller, 90);
lv_obj_set_align( ui_humi_roller, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_humi_roller, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_humi_roller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humi_roller, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_humi_roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_humi_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_humi_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_humi_roller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_humi_roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_humi_roller, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_humi_roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_humi_roller, &lv_font_montserrat_14, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_humi_roller, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_humi_roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label_Temp1 = lv_label_create(ui_footer_group);
lv_obj_set_width( ui_Label_Temp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Temp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Temp1, 60 );
lv_obj_set_y( ui_Label_Temp1, -14 );
lv_label_set_text(ui_Label_Temp1,"TEMP.");
lv_label_set_recolor(ui_Label_Temp1,"true");
lv_obj_set_style_text_color(ui_Label_Temp1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Temp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Temp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Temp1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Humi1 = lv_label_create(ui_footer_group);
lv_obj_set_width( ui_Label_Humi1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Humi1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Humi1, 0 );
lv_obj_set_y( ui_Label_Humi1, -14 );
lv_obj_set_align( ui_Label_Humi1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label_Humi1,"HUMI.");
lv_label_set_recolor(ui_Label_Humi1,"true");
lv_obj_set_style_text_color(ui_Label_Humi1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Humi1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Humi1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Humi1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BTN_Choose = lv_img_create(ui_footer_group);
lv_img_set_src(ui_BTN_Choose, &ui_img_btn_print_down_png);
lv_obj_set_width( ui_BTN_Choose, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Choose, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Choose, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_BTN_Choose, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Choose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BTN_Choose_Top = lv_img_create(ui_BTN_Choose);
lv_img_set_src(ui_BTN_Choose_Top, &ui_img_btn_print_top_off_png);
lv_obj_set_width( ui_BTN_Choose_Top, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_BTN_Choose_Top, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_BTN_Choose_Top, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BTN_Choose_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BTN_Choose_Top, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BTN_Choose_Top, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_BTN_Choose_Top, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_BTN_Choose_Top, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BTN_Choose_Top, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_shadow_opa(ui_BTN_Choose_Top, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_width(ui_BTN_Choose_Top, 9, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_spread(ui_BTN_Choose_Top, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_x(ui_BTN_Choose_Top, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_ofs_y(ui_BTN_Choose_Top, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Image_Choose = lv_img_create(ui_BTN_Choose_Top);
lv_img_set_src(ui_Image_Choose, &ui_img_sure_png);
lv_obj_set_width( ui_Image_Choose, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image_Choose, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Image_Choose, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Choose, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Choose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_BTN_Choose_Top, ui_event_BTN_Choose_Top, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setting_param, ui_event_setting_param, LV_EVENT_ALL, NULL);

}
